### ISSUE TITLE
provide releases

### ISSUE THREAD

**Issue by gwutz** [sytsereitsma/mdbook-plantuml#10]
Is it possible to provide releases for the preprocessor. I am not able to compile it in corporate network and would really use this if possible.

**Comment by sytsereitsma** [comment]
Missed your message, my github emails end up in the spam folder, still need to change that.

I'll see if and how this can be realized. Which platform(s)?

**Comment by gwutz** [comment]
Windows 10 64bit. I really appreciate your response!

**Comment by sytsereitsma** [comment]
I created an new release [here](https://github.com/sytsereitsma/mdbook-plantuml/releases/tag/v0.3.0_with_binary). It includes the windows binary from my system, hopefully this works for you.
