### ISSUE TITLE
Plantuml executable vs jarfile

### ISSUE THREAD

**Issue by krampenschiesser** [sytsereitsma/mdbook-plantuml#18]
Plantuml is currently distrubted as a jarfile that needs a java installation in order to run.
I cannot find any downloadable executable on their website.
Where do you get the executable from and would you add support for the jarfile?

**Comment by sytsereitsma** [comment]
Sorry, I misunderstood the question. As far as I know there is no executable that can be downloaded directly.
If you install plantuml with [Chocolatey ](https://chocolatey.org/) as I did, you will get an executable that wraps the Java call though,
