### ISSUE TITLE
maintenance status?

### ISSUE THREAD

**Issue by danieleades** [sytsereitsma/mdbook-plantuml#27]
I can see it's been a while since there have been any new commits. Is this project still actively maintained?

**Comment by sytsereitsma** [comment]
Hi Daniel. It's resting :-)
I can hardly find time to do any coding at the moment, I occasionally pick it up, but have been unable to add new features or updates for a while indeed.

Regards,

Sytse

**Comment by danieleades** [comment]
> Hi Daniel. It's resting :-)
> I can hardly find time to do any coding at the moment, I occasionally pick it up, but have been unable to add new features or updates for a while indeed.
> 
> Regards,
> 
> Sytse

That's understandable. Life has a way of getting in the way!

I'm finding this crate super helpful, so I'd love to help if I possibly can. See #26
