### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by sytsereitsma** [sytsereitsma/mdbook-plantuml#7]
The preprocessor uses stdout to communicate with the main mdBook process, so logging errors is kinda cumbersome. Simply capture the entire error chain and display it instead of the diagram.

PlantUML itself does not generate an error when a user forgets to add the @startuml/@enduml sections, resulting in no diagram file being generated. This in turn prints the rather unhelpful error message ```No such file or directory (os error 2)```. Add handling for this too.

**Comment by Michael-F-Bryan** [comment]
There's a better way of doing this. The preprocessor communicates with `mdbook` via STDIN and STDOUT, but STDERR is [deliberately passed through][1] to the parent console.

As an example, in `mdbook-linkcheck` I [write diagnostics to STDERR][2] so users get pretty error messages when their links are broken.

![Screenshot from 2019-11-05 20-02-50](https://user-images.githubusercontent.com/17380079/68206262-47f17900-0007-11ea-81b4-9bb61da2f5ee.png)

[1]: https://github.com/rust-lang/mdBook/blob/f2cb601c1194257ae2dd66effaa2fc6ac72799c0/src/preprocess/cmd.rs#L101
[2]: https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/ceae3b56afc0822a2c9d321c76a297366855930d/src/lib.rs#L142
