### ISSUE TITLE
Is there a way to force a large diagram to fit a page in mdbook with this add-on?

### ISSUE THREAD

**Issue by GeoffMurray** [sytsereitsma/mdbook-plantuml#79]
We have some diagrams where they are currently sligthly long for the page output when we also generate PDF from the source. 

Do you have any suggestions for trying to get an image to fit  ?

**Comment by sytsereitsma** [comment]
The only thing I can think of is adding a CSS stylesheet to the book with a [`max-height`](https://developer.mozilla.org/en-US/docs/Web/CSS/max-height) property for images. Unfortunately this will affect all images in the book.
In your css file:
```css
img {
  max-height:500px
}
```

And in your book you should add an [`additional-css`](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options) line to the html renderer configuration.

**Comment by GeoffMurray** [comment]
We found something similar. We are using this for now. In our case, we want it to be the maxium of the page size in height, but no more. We wanted that consistent across all our created diagrams. Seems to be working very well for us. 

<style>
img {
    max-height: 100vh;
    display: block;
    margin: 0 auto;
}
</style>
